// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCGF-FE8L09oMSRXZs2bPj-txZkbIeNa8k',
    appId: '1:440506479780:web:e4e51edd25c8031aefa231',
    messagingSenderId: '440506479780',
    projectId: 'taskmanagement-88aa3',
    authDomain: 'taskmanagement-88aa3.firebaseapp.com',
    storageBucket: 'taskmanagement-88aa3.appspot.com',
    measurementId: 'G-WQ80GK2TZZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCMsAFQaCzgXTqim_RFFXX0QI95A8DGE14',
    appId: '1:440506479780:android:a2b81988d34f040eefa231',
    messagingSenderId: '440506479780',
    projectId: 'taskmanagement-88aa3',
    storageBucket: 'taskmanagement-88aa3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC5IMl3Ps40qniQvrRx-i7O1zGMjn5njKM',
    appId: '1:440506479780:ios:b48f3b3b99aa94e5efa231',
    messagingSenderId: '440506479780',
    projectId: 'taskmanagement-88aa3',
    storageBucket: 'taskmanagement-88aa3.appspot.com',
    iosClientId: '440506479780-kh9up6omd97td97qsc0u1u3o7t5b377s.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterRiverpodTaskManagement',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC5IMl3Ps40qniQvrRx-i7O1zGMjn5njKM',
    appId: '1:440506479780:ios:66988081dfd62174efa231',
    messagingSenderId: '440506479780',
    projectId: 'taskmanagement-88aa3',
    storageBucket: 'taskmanagement-88aa3.appspot.com',
    iosClientId: '440506479780-qjl01reerrnjsh07i95787hpu2hodmoj.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterRiverpodTaskManagement.RunnerTests',
  );
}
